### ISSUE TITLE
Unable to authorize with Yammer.com

### ISSUE THREAD

**Issue by fehwalker** [aphyr/yamr#1]
When I try to authorize with Yammer.com, I get:

Authorization Error

The application Yamr can not be authorized in your network. Please contact the application author.

Application
Yamr
Author (Organization Name)
Kyle Kingsbury

**Comment by aphyr** [comment]
Actually, I'm having trouble reproducing this. Could you pull from github, try it again, and see if the authorize url displayed in the console looks correct? Should be something like "https://yammer.com/oauth/authorize?oauth_token=8u3dsa..."

Do you get this message when you click authorize? Or as soon as you load that authorization page?

**Comment by unixfanatic** [comment]
Same problem here. App starts and opens browser window to ... https://www.yammer.com/oauth/authorize?oauth_token=ugzH8xT8OV1Rz2OTtKER. The brower URL becomes ... https://www.yammer.com/electric-cloud.com/oauth/invalid_client_application?client_application_id=1144. And the page from Yammer reads ...

Authorization Error
The application Yamr can not be authorized in your network. Please contact the application author.

Application
Yamr
Author (Organization Name)
Kyle Kingsbury

**Comment by gerrywastaken** [comment]
Same problem here, anything to do with this? https://www.yammer.com/api_oauth_security_addendum.html

**Comment by timschristie** [comment]
I managed to get this application to correctly authorize. I'll leave the steps I took here to help anyone else who has the same problem described above.

Firstly, you will need to visit https://www.yammer.com/ionata.com.au/client_applications/new and register your copy of the Yamr client as a new application. (Fill in the details as you see fit.)

After submitting that page, you will be given a Consumer (Application) Key and a Consumer (Application) Secret. Use these to modify ./bin/yamr/lib/yamr/oauth.rb and replace the values in OAUTH_APP_KEY and OAUTH_APP_SECRET with the values you just received.

After doing this, the application will be able to authorize correctly to your network.

https://www.yammer.com/api_doc.html also has instructions for making the same Consumer (Application) Key / Secret work for anyone, saying: "If you would like your application to be able to access additional networks, or would like to make it available for public use, please send your registered email address, and client key to api@yammer-inc.com."

**Comment by ecadmin** [comment]
Error fetching new messages: RuntimeError: 400 Bad request
