### ISSUE TITLE
Minor changes

### ISSUE THREAD

**Issue by darac** [aphyr/yamr#2]
I've made a couple of changes to lib/yamr/client.rb to get Yamr to start on my computer.

Firstly, I've changed the BROWSER_CMD from 'chromium-browser' to 'sensible-browser' which picks the user's default browser on Debian-based systems.

Secondly, I had to add ":proxy => "http://proxy.mycompany.com" to the call to OAuth::Consumer.new as I can't make connections off the corporate network without going through the proxy. It would be nice if you could pick up the correct location either from $http_proxy or through Gnome's "System Default".

However, I'm also hitting the problem that fehwalker had of not being able to authorise Yamr.

**Comment by rnts08** [comment]
I've changed chromium-browser to sensible-browser aswell, atleast that allows me to start the app. Allthough, I also have the same problem with authentication. 

Authorization Error

The application Yamr can not be authorized in your network. Please contact the application author.

Application
    Yamr
Author (Organization Name)

##     Kyle Kingsbury 

On the console:

Opening https://www.yammer.com/oauth/authorize?oauth_token=FnThH8CEdSX9B5lpopgaYw for authorization
