### ISSUE TITLE
`gem_original_require': no such file to load -- webkit (LoadError)

### ISSUE THREAD

**Issue by zhaq** [aphyr/yamr#4]
Hi,

When I try to run my yamr on a ubuntu 10.04, I get the following...

/usr/local/lib/site_ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require': no such file to load -- webkit (LoadError)
    from /usr/local/lib/site_ruby/1.8/rubygems/custom_require.rb:31:in`require'
    from ./../lib/yamr.rb:9
    from ./yamr:3:in `require'
    from ./yamr:3

I do have libwebkit\* installed!

**Comment by aphyr** [comment]
Did you build and install the ruby webkit bindings? Instructions in the 
wiki.

--Kyle

**Comment by zhaq** [comment]
Thanks a lot aphyr. 
After building webkit bindings, now I get this...

/usr/lib/ruby/1.8/net/http.rb:560:in `initialize': getaddrinfo: Name or service not known (SocketError)
    from /usr/lib/ruby/1.8/net/http.rb:560:in`open'
    from /usr/lib/ruby/1.8/net/http.rb:560:in `connect'
    from /usr/lib/ruby/1.8/timeout.rb:53:in`timeout'
    from /usr/lib/ruby/1.8/timeout.rb:93:in `timeout'
    from /usr/lib/ruby/1.8/net/http.rb:560:in`connect'
    from /usr/lib/ruby/1.8/net/http.rb:553:in `do_start'
    from /usr/lib/ruby/1.8/net/http.rb:542:in`start'
    from /usr/lib/ruby/1.8/net/http.rb:1035:in `request'
    from /usr/lib/ruby/gems/1.8/gems/oauth-0.4.5/lib/oauth/consumer.rb:164:in`request'
    from /usr/lib/ruby/gems/1.8/gems/oauth-0.4.5/lib/oauth/consumer.rb:197:in `token_request'
    from /usr/lib/ruby/gems/1.8/gems/oauth-0.4.5/lib/oauth/consumer.rb:139:in`get_request_token'
    from ./../lib/yamr/client.rb:41:in `auth'
    from ./../lib/yamr/client.rb:311:in`start'
    from ./yamr:5

**Comment by aphyr** [comment]
Sorry dude, I haven't used yamr in 2 years, and have some other big 
stuff on my plate now. The host it's trying to connect to probably 
doesn't exist any more. Feel free to submit a pull req.

--Kyle

**Comment by zhaq** [comment]
I don't do ruby, so I am giving up. Thanks for all your help.
